### ISSUE TITLE
[2.3rc2] Cannot create or edit badges

### ISSUE THREAD

**Issue by Swennet** [hgtonight/Application-Yaga#142]
When editing a badge, or creating a new badge, the form will always return an error. It seems like there is a bug in the validation part of the badge input system.

For example, when editing default the "First Anniversary" badge, without editing any of it's settings, and pressing Save, it will return the following error message:

> Duration is required.
> Period is required.

When creating a new "Holiday Visit" type badge, entering all the required fields correctly, it will return:

> Month is required.
> Day is required.

**Comment by Swennet** [comment]
Fixed this by commenting out a (seemingly rather hacky) if statement from /yaga/controllers/class.badgecontroller.php

```
          // Find the rule criteria
          $FormValues = $this->Form->FormValues();            
          $Criteria = array();
          foreach($FormValues as $Key => $Value) {
            //if(substr($Key, 0, 7) == '_Rules/') {
              $Criteria[$Key] = $Value;
            //}
          }
```

**Comment by PatrickGriffiths** [comment]
This is still an issue, I tried to comment out like suggested above and after selecting save the page goes white and nothing works.

**Comment by PatrickGriffiths** [comment]
This issue still exists even with the above alteration I can't seem to edit anything.
